name: 18 - 1 - Reusable Workflows - Reusable Definition
on :
    workflow_call:
      inputs:
        target-directory:
            type: string
      outputs:
        build-status:
            description: The status of the build process
            value: ${{jobs.deploy.outputs.build-status}}
    
        url:
            description: The url of the deployed version
            value: ${{jobs.deploy.outputs.url}}
jobs:
    deploy:
        outputs:
          build-status: ${{steps.build.outputs.build-status}}
          url : ${{steps.deployment.outputs.url}}
        runs-on: ubuntu-latest
        steps:
          - name : Checkout Code
            uses: actions/checkout@v4
          - name : Build
            id : build
            run: |
                echo "Building using directory ${{inputs.target-directory}}"
                echo "build-status=success" >> "$GITHUB_OUTPUT"
          - name: Deploy
            id : deployment
            run : |
                echo "deploying Artifacts"
                echo "url=https://www.google.com" >> "$GITHUB_OUTPUT"
