name : QueryInjection
on:
  pull_request:
jobs:
  checkPR:
    runs-on: ubuntu-latest
    env:
       title: ${{ github.event.pull_request.title }}
    steps:
      - uses: actions/checkout@v4
      - name: Check If the PR is feature branch
        run: |
          
          if [[ $title =~ ^feat ]]; then
          echo "PR is a feature "
          exit 0
          else
          echo "PR is not a feature"
          exit 1
          fi
          
